### ISSUE TITLE
Durations are of type java.time.Duration not kotlin.time.Duration

### ISSUE THREAD

**Issue by WeisSeb** [simonhauck/gradle-release-plugin#52]
## Describe the bug

Durations (e.g delayBeforePush) have to be provided as `java.time.Duration` objects. I would expect to be able to provide `kotlin.time.Duration` objects instead. Is this intended?

## Current behavior

```kotlin
release {
    delayBeforePush = 1.minutes 
}
```
causes a `Type mismatch: inferred type is kotlin.time.Duration but Property<java.time.Duration> was expected` compile error
## Expected behavior

`kotlin.time.Duration` objects can be used

## 📱 Tech info

- Plugin Version: 1.0.0-RC2

**Comment by simonhauck** [comment]
That was not intentional.
I checked the example and tried to replace it with the Kotlin duration. I noticed that the test for Gradle versions smaller than 7.2 are failing grade bumped there the Kotlin version from 1.4.31 to 1.5.21.

To keep the compatibility to older versions, I would leave this as it is right now.
